version: '3.8'

services:
  # ponder:
  #   build: .
  #   ports:
  #     - "42069:42069"
  #   environment:
  #     - NODE_ENV=production
  #     - PONDER_RPC_URL_17000=https://holesky.gateway.tenderly.co
  #     - PONDER_RPC_URL_43113=https://rpc.ankr.com/avalanche_fuji
  #     - DATABASE_URL=postgresql://ponder:ponderpass@postgres:5432/ponder_db
  #     - DATABASE_SCHEMA=my_schema
  #     - PONDER_TELEMETRY_DISABLED=true
  #     - RABBITMQ_URL=amqp://rabbitmq:5672
  #   volumes:
  #     - ponder-data:/app/.ponder
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy

  # postgres:
  #   image: postgres:15-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=ponder
  #     - POSTGRES_PASSWORD=ponderpass
  #     - POSTGRES_DB=ponder_db
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ponder -d ponder_db"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  ponder-data:
  postgres-data:
  rabbitmq-data: 