version: "3.8"

services:
  ponder:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "42069:42069"
    environment:
      - NODE_ENV=production
      - PONDER_RPC_URL_17000=https://ethereum-holesky.blockpi.network/v1/rpc/af524eebf9bf7e73f1b38522c9dd98618cbaf28e
      - PONDER_RPC_URL_43113=https://avalanche-fuji.blockpi.network/v1/rpc/25ac5e33dc0a9af23d949c93bc23f8e02be5624e
      - PONDER_WS_URL_17000=wss://ethereum-holesky.blockpi.network/v1/ws/af524eebf9bf7e73f1b38522c9dd98618cbaf28e
      - PONDER_WS_URL_43113=wss://avalanche-fuji.blockpi.network/v1/ws/25ac5e33dc0a9af23d949c93bc23f8e02be5624e
      - DATABASE_URL=
      - DATABASE_SCHEMA=my_schema
      - PONDER_TELEMETRY_DISABLED=true
      - RABBITMQ_URL=amqp://guest:guest@host.docker.internal:5672
    volumes:
      - ponder-data:/app/.ponder
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  ponder-data:
  rabbitmq-data:
